### ISSUE TITLE
Enhancement: shortcut to manually open media control overlay

### ISSUE THREAD

**Issue by roughnecks** [Hual/foo_mediacontrol#3]
Hi there, 
I'm using your software since a couple days and it's really fine.
I'd like to request a feature so that it'd be possibile to open the overlay whenever I want - just so I can check which song is currently playing.

Excuse me if this is already possible, tried to google up for "windows 10 media control overlay shortcut" to no avail.

Thanks

**Comment by Hual** [comment]
That's sadly not possible because of how the media controls work.
