### ISSUE TITLE
Possible to display the interface on song-change?

### ISSUE THREAD

**Issue by DeadSix27** [Hual/foo_mediacontrol#4]
Currently it only does show up when you either:

- Change volume
- Change track MANUALLY
- Pause/Play/Stop

Is it possible to display the overlay when foobar changes the track by itself (after it finished)?

**Comment by Hual** [comment]
That's sadly not possible because of how the media controls work.

**Comment by DeadSix27** [comment]
Is there not an event in foobar you can hook into that gets triggered when a song changes and then display the info thing? (I never looked into the foobar sdk, so I'm just guessing this)

**Comment by Hual** [comment]
No, because the interface is only shown when Windows decides - when you press media keys.

**Comment by Onurtag** [comment]
Would it be possible to make it show up when you start a stopped song? 
E.g. Stop media button > Wait for the volume panel to fade out > start (play/pause) media button
or Stop media button > Wait for the volume panel to fade out > Next/previous media button  

Thanks for the awesome component. The default foobar 1.4 UI has something similar but it doesn't remove the song from the volume panel when you stop playback so this one is better.
