### ISSUE TITLE
foobar2000 appears to have multiple audio sessions but only one is active

### ISSUE THREAD

**Issue by roughnecks** [Hual/foo_mediacontrol#5]
Here's what I mean: https://i.imgur.com/6ZUrX6o.png

This is not happening when foo_mediacontrol is uninstalled.

**Comment by Hual** [comment]
Any ideas how I could reproduce it?

**Comment by roughnecks** [comment]
Well, for me that doubled session appears as soon as I install foo_mediacontrol and reboot foobar.
It always stays at 100% and looks like a fake one (doesn't change volume).

**Comment by roughnecks** [comment]
https://i.imgur.com/qPubyYx.gifv

**Comment by Hual** [comment]
This is due to the fact that the background media player starts a background process.
