### ISSUE TITLE
Foobar complains the plugin is not for this version

### ISSUE THREAD

**Issue by digfish** [Hual/foo_mediacontrol#6]
When I try load the DLL when foobar is launched it fals with the following error message:
`Failed to load DLL: foo_mediacontrol.dll
Reason: This component is missing a required dependency, or was made for different version of foobar2000.`
I used the versions 1.3.17 and  1.4 beta 2 . 
It states that it is missing a dependency !? Which dependency is !?

**Comment by rhalfkann** [comment]
Same here with versions 1.3.16 and 1.3.17.

**Comment by Hual** [comment]
I can't reproduce it on 1.3.17. Do you have the Visual C++ 2015 redistributable installed?

**Comment by digfish** [comment]
I'm using the compiled version. Not using development tools.

2017-12-31 11:38 GMT+00:00 Nikola Yanakiev <notifications@github.com>:

**Comment by rhalfkann** [comment]
At least I thought I had. But as it turned out, only the x64 package. Installed the x86 version and everything works as expected. Feeling a bit stupid now... ;) Thanks for the quick reply!

**Comment by Hual** [comment]
I'll add a statically linked build just in case.

@digfish the runtime is required to run it, not just to build it.

**Comment by digfish** [comment]
Hi,

thank you all for your quick replies.
How I'm going to use the runtime !? It's not possible to use the .dll !?
Can you upload it to the releases !?

Thanks again

2017-12-31 13:15 GMT+00:00 Nikola Yanakiev <notifications@github.com>:

**Comment by rhalfkann** [comment]
Just download and install the "Visual C++ Redistributable for Visual Studio 2015" x86 package from microsoft.com, restart foobar2000 and the component should load. 

The runtime isn't something you need to actively use. It just provides libraries which software built with Visual Studio 2015 needs to function. That's the actual dependency the error message refers to.

Or you could wait for @Hual to upload the statically linked DLL which wouldn't need the runtime to be installed on your machine.

**Comment by digfish** [comment]
OK, I Installed the Visual C++ Library for windows you were talking about. And the plugin worked right away. Thank you @Hual @rhalfkann for your time.

**Comment by Hual** [comment]
I've been trying to link the C++ runtime statically but there's a limitation with WinRT such that you can't link the CRT statically. I'll try a few different things like separating WinRT code in a static library but can't promise I'll succeed.

**Comment by Hual** [comment]
Not possible, sadly.
