### ISSUE TITLE
fatal error C1107

### ISSUE THREAD

**Issue by ssooc** [Hual/foo_mediacontrol#7]
fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable

**Comment by azurefx** [comment]
**Tested on Visual Studio 2017 Community 15.6.6**
The path to platform.winmd is different on VS2017 (e.g. "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\vcpackages"). Add this to /AI option and it compiles.
配置属性 > C/C++ > 常规 > 其他 #using 指令
(Configuration Properties > C/C++ > General > Additional #using Directories)
